// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// GetBinaryDosageFormat
Rcpp::List GetBinaryDosageFormat(const std::string& binaryDosageFilename, const unsigned int nSub, const unsigned int nSNPs);
RcppExport SEXP _POCBinaryDosageCOH_GetBinaryDosageFormat(SEXP binaryDosageFilenameSEXP, SEXP nSubSEXP, SEXP nSNPsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type binaryDosageFilename(binaryDosageFilenameSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type nSub(nSubSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type nSNPs(nSNPsSEXP);
    rcpp_result_gen = Rcpp::wrap(GetBinaryDosageFormat(binaryDosageFilename, nSub, nSNPs));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _POCBinaryDosageCOH_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// WriteBinaryDosage
int WriteBinaryDosage(const Rcpp::NumericMatrix& x, const int numSubjects, const int numSNPs, const std::string& filename);
RcppExport SEXP _POCBinaryDosageCOH_WriteBinaryDosage(SEXP xSEXP, SEXP numSubjectsSEXP, SEXP numSNPsSEXP, SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int >::type numSubjects(numSubjectsSEXP);
    Rcpp::traits::input_parameter< const int >::type numSNPs(numSNPsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(WriteBinaryDosage(x, numSubjects, numSNPs, filename));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_POCBinaryDosageCOH_GetBinaryDosageFormat", (DL_FUNC) &_POCBinaryDosageCOH_GetBinaryDosageFormat, 3},
    {"_POCBinaryDosageCOH_rcpp_hello_world", (DL_FUNC) &_POCBinaryDosageCOH_rcpp_hello_world, 0},
    {"_POCBinaryDosageCOH_WriteBinaryDosage", (DL_FUNC) &_POCBinaryDosageCOH_WriteBinaryDosage, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_POCBinaryDosageCOH(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
